version: '3.9'
name: laradock-task
networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:pro 
    volumes_from:
      - php
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  
  mysql:
    image: mysql:latest
    
    restart: unless-stopped
    tty: true
    ports:
      - "4036:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: task
      MYSQL_USER: task
      MYSQL_PASSWORD: task
      MYSQL_ROOT_PASSWORD: task
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
    
  php:
    image: php:8-fpm
    build:
      context: src/
      dockerfile: Dockerfile
    
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel